### ISSUE TITLE
[Feature Request] Dumping boot9, boot11, and otp

### ISSUE THREAD

**Issue by Dimensional** [derrekr/fastboot3DS#18]
I haven't been able to figure out if this is even possible, failing left and right, at dumping the same files that boot9strap can dump when pressing and holding certain buttons at boot. I can't be sure if it seems like it would be required, but since it is a feature in the original b9s, could this be included to make a more inclusive bootloader?

**Comment by profi200** [comment]
This is not supported at the moment but it's on our todo list.

**Comment by profi200** [comment]
This has been added now. Beta release soon™.
