### ISSUE TITLE
Changing the splash time

### ISSUE THREAD

**Issue by j0w0** [derrekr/fastboot3DS#21]
Right now I love the new splash function, however it goes a bit too quick for a custom splash with keybinds. Could there be a setting to extend or shorten the splash display time? (like luma nightly, but maybe more precise)

**Comment by d0k3** [comment]
It would make the menu more complicated, but it also may be a worthy addition. We'lll discuss it.

**Comment by d0k3** [comment]
Okay, it's in there (in the nightly). Testing is appreciated.
