### ISSUE TITLE
Uninstalling?

### ISSUE THREAD

**Issue by DynamicDonkey** [derrekr/fastboot3DS#22]
I'm trying to reset all modifications without reflashing the NAND. Is there a way to remove Fastboot3DS, safely?

**Comment by d0k3** [comment]
You know, GitHub issues is for bug reports / feature requests and not a support place?

Anyways, there's a GM9 script for uninstalling boot9strap. It will also work for uninstalling fastboot3ds and any other bootloader. As for where to get it, how to use it, you're on your own. Ask in some support place (GBAtemp, Discord, IRC).
