### ISSUE TITLE
trying to compile

### ISSUE THREAD

**Issue by jimmyjxD** [derrekr/fastboot3DS#23]
I'm trying to compile a clean fastboot3ds and I believe I have all the requirements, but I get this error.
C:/Users/willi/Desktop/fastboot3DS-1.0/fastboot3DS-1.0/arm9/../source/arm9/firmwriter.c:166:28: error: expected expression before '<<' token
  if(vers < ((u32)VERS_MAJOR<<16 | VERS_MINOR)) return UPDATE_ERR_DOWNGRADE;
                            ^~
make[2]: *** [/opt/devkitpro/devkitARM/base_rules:85: firmwriter.o] Error 1
make[2]: *** Waiting for unfinished jobs....
C:/Users/willi/Desktop/fastboot3DS-1.0/fastboot3DS-1.0/arm9/../thirdparty/fatfs/ff.c: In function 'f_setlabel':
C:/Users/willi/Desktop/fastboot3DS-1.0/fastboot3DS-1.0/arm9/../thirdparty/fatfs/ff.c:5062:2: warning: this 'for' clause does not guard... [-Wmisleading-indentation]
  for (slen = 0; (UINT)label[slen] >= ' '; slen++) ; /* Get name length */
  ^~~
C:/Users/willi/Desktop/fastboot3DS-1.0/fastboot3DS-1.0/arm9/../thirdparty/fatfs/ff.c:5082:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'for'
  { /* On the FAT/FAT32 volume */
  ^
make[1]: *** [Makefile:112: build] Error 2
make: *** [Makefile:31: checkarm9] Error 2

help would very much be appreciated ^^

**Comment by profi200** [comment]
Is git installed inside msys2? It is required to get the version infos out of the git repo.

**Comment by jimmyjxD** [comment]
I have git installed,but I compile all my stuff with cmd. So I don't think I have git in msys2 but it is in PATH.

**Comment by profi200** [comment]
Do you have any other toolchains installed? It sounds like you are using the wrong make if it can't find git. Try to open the msys2 shell and compile in there.

**Comment by profi200** [comment]
In this case i'm not sure what's wrong. It sounds like your devkitARM/msys2 install is borked somehow.

**Comment by d0k3** [comment]
@jimmyjxD - can you just uninstall and reinstall your devkitARM? Or, has this been solved for you already?

**Comment by jimmyjxD** [comment]
it hasn't been solved unfortunately, and I currently don't have access to my pc but I will have access to one in a few days. I also never wanted to reinstall devkitpro because it was hard to setup an environment that can compile stuff like luma and godmode9 and if it borks it it's gonna be difficult to understand what broke :/

**Comment by d0k3** [comment]
devkitPro *should* be really easy to reinstall, and you're not required to touch anything else (git, etc). I do understand why you don't want to, it's just pretty hard to suggest anything else.

**Comment by jimmyjxD** [comment]
yeah i see,I'll try uninstalling it when I can

**Comment by jimmyjxD** [comment]
just don't wanna bork anything

**Comment by d0k3** [comment]
Okay, this has been open with no info added for a while. @jimmyjxD - did you get this working? As I wrote, no other choice than to uninstall and reinstall the tool chain. Otherwise there's no way to get this fixed.

**Comment by d0k3** [comment]
Okay, I'm assuming this solved. @jimmyjxD - feel free to contact us if you still can't compile fastboot3ds. Closing this now.

**Comment by urherenow** [comment]
I'm running into this issue, and all of my toolchains are up to date. I have no internet access on my personal computer at the moment, but I can compile Luma3ds, Godmode9, boot9strap, etc and all manner of Switch stuff as well. As I don't have internet on my personal computer, I am, however, building from a zipped download of the current master (I can't do a git clone right now).

**Comment by profi200** [comment]
You can try and edit the makefile temporarily to assign numbers to these 2 defines. It's a dirty workaround. Keep that in mind.
