### ISSUE TITLE
boot9.bin and boot11.bin not appearing in godmode9 after installing fastboot3ds

### ISSUE THREAD

**Issue by Muda42** [derrekr/fastboot3DS#27]
I don't know if it is normal but after installing fastboot3ds the boot9.bin and boot11.bin just disappeared

**Comment by d0k3** [comment]
Sooo... What really happened there, @Muda42?

**Comment by Muda42** [comment]
No nothing i figured it out (Sorry im a bit a noob)

**Comment by profi200** [comment]
fastboot3DS doesn't leave boot9/11 in memory so GodMode9 can't pick it up. But you can dump them in fastboot3DS to your SD card.
