### ISSUE TITLE
[Enhancement] Wider display of path and filename in boot menu

### ISSUE THREAD

**Issue by jelbo** [derrekr/fastboot3DS#28]
See title. I have multiple .firm's to choose from, but the names are not fully displayed because the display width is limited. There is enough space on the screen though. Please widen this display.

**Comment by d0k3** [comment]
Can you provide us with a screenshot? Photo is actually enough.

**Comment by jelbo** [comment]
Boot slot selection shows a truncated path and filename view:

![fastboot3ds_02](https://user-images.githubusercontent.com/7387027/49031701-01ff2480-f1ab-11e8-8c2e-45ea1a6f9970.jpg)

Same for the initial boot slot setup screen:

![fastboot3ds_01](https://user-images.githubusercontent.com/7387027/49031766-307cff80-f1ab-11e8-9935-82f9bab9c9c0.jpg)

Boot from file shows a wide file list. Maybe this can be used as a basis?

**Comment by derrekr** [comment]
Thanks for the photos!
We found the code that's causing this issue and we are going fix it.

**Comment by d0k3** [comment]
Alright, I increased the limit. If you want to try it, here's a test build:
https://f.secretalgorithm.com/Vas9O/fastboot3ds.firm
