### ISSUE TITLE
Bricked 3DS :(

### ISSUE THREAD

**Issue by RiddickPower** [derrekr/fastboot3DS#29]
My 3DS bricked today because i updated to 11.9
I dont know why, i hacked a 3DS yesterday and nothing happened(used b9s for that console)

Tried updating boot.firm
Tried EVERYTHING!

;(

**Comment by d0k3** [comment]
This doesn't have anything to do with fb3DS, that much is sure. What CFW are you using? What happens if you hold the HOME button on boot?

**Comment by RiddickPower** [comment]
Luma. Happens nothing. Just a black screen with screen on

**Comment by RiddickPower** [comment]
Also without the SD card

**Comment by RiddickPower** [comment]
EDIT: I used ReiNand CFW for the update

**Comment by Wolfvak** [comment]
https://gbatemp.net/threads/source-release-reinand-cfw.394309/page-322#post-8414585

It's a ReiNand bug, go to them for support

**Comment by RiddickPower** [comment]
Okay thanks

**Comment by RiddickPower** [comment]
Okay thanks!
