### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by Multimegamander** [derrekr/fastboot3DS#35]
source/arm9/firmwriter.c 
166:28 error: expected expression before '<<' token
  if(vers < ((u32)VERS_MAJOR<<16 | VERS_MINOR)) return UPDATE_ERR_DOWNGRADE;
                            ^~
make[2]: *** [/opt/devkitpro/devkitARM/base_rules:84: firmwriter.o] Error 1

**Comment by profi200** [comment]
Do you have git installed inside the devkitPro provided msys2 (pacman -Syu git)? (if you are using Linux install git through your package manager).

**Comment by Multimegamander** [comment]
I do have Git

**Comment by Multimegamander** [comment]
but, does it need to be part of a git, bc I have it local?

**Comment by profi200** [comment]
Did you git clone or did you download a zip file from the releases section? Because the zip files are missing the git files so it can't get the version infos and it will fail on compilation like that.

**Comment by Multimegamander** [comment]
oh, I downloaded

**Comment by Multimegamander** [comment]
it worked, my bad :P
