### ISSUE TITLE
What does Error -10 mean?

### ISSUE THREAD

**Issue by daemonspudguy** [derrekr/fastboot3DS#36]

**Comment by profi200** [comment]
What did you do causing this error? We need more infos to be able to help you.

**Comment by daemonspudguy** [comment]
Loading some payloads creates a Firm Verify Error with that code.

**Comment by derrekr** [comment]
The error indicates the file does not contain a valid FIRM header (bad magic).
Most likely your payload was not intended to be treated as FIRM.

**Comment by daemonspudguy** [comment]
oh
