### ISSUE TITLE
Default dump path shouldn't be sdmc:/3DS/

### ISSUE THREAD

**Issue by ParzivalWolfram** [derrekr/fastboot3DS#37]
sdmc:/3DS/ is where things like HBL payloads and homebrew app data goes, it would clutter up the folder further. I would propose a system as such:
NAND backups: sdmc:/backups/
boot*/otp dumps: sdmc:/dumps/

**Comment by SirNapkin1334** [comment]
Well, there's already an sdmc:/fb3ds folder, isn't there? Maybe those can be a subfolder of that folder.

**Comment by derrekr** [comment]
We think that the majority of our users prefer the current path. Build the project from source if you would like to use a different path.

**Comment by ParzivalWolfram** [comment]
Silence isn't always agreement, but okay.

**Comment by profi200** [comment]
This probably got lost. We actually discussed this a while ago and came to the conclusion, that a path change may break for example tutorials or similar and is therefore not an option. I also think another folder at the root is not a good thing.
Are there even enough homebrews around that throwing files in /3ds is a problem? The only realistic approach is a folder inside /3ds imho.

**Comment by ParzivalWolfram** [comment]
That would work, but for those using lots of 3DSX homebrew, just dumping
shit to /3ds would further muddy up things and potentially stop allowing
GM9 to manage everything in there.
