### ISSUE TITLE
Broken error screen when autoboot slot fails on quiet mode.

### ISSUE THREAD

**Issue by Cuphat** [derrekr/fastboot3DS#4]
If the autoboot slot fails to load on quiet mode, this is how the error message displays for me:

![img_20171224_202511](https://user-images.githubusercontent.com/15843710/34330395-0d765a56-e8ea-11e7-9a88-885b9c3a351f.jpg)

**Comment by d0k3** [comment]
Okay, ugh. This has something to do with the screen not initializing properly. We'll look into that.

**Comment by Cuphat** [comment]
For a bit more information, the menu looks fine after pressing B or Home. :)

**Comment by profi200** [comment]
Screens acting up just like with the splash. Need to look into it later.

**Comment by profi200** [comment]
Can you or anyone else with the same problem try this build? https://dl.dropboxusercontent.com/s/fjq1546waja2nog/fastboot3DS.firm

Note: This build is not signed. Please use GodMode9 to install it.

**Comment by Cuphat** [comment]
I'm still having the same issue on that build.

**Comment by profi200** [comment]
I can reproduce it on my own N3DS XL. I thought i had this fixed but apparently not. Working on debugging it.

**Comment by profi200** [comment]
Fixed in 1c6190d.
