### ISSUE TITLE
Cannot open menu (home button broken)

### ISSUE THREAD

**Issue by marcotw2** [derrekr/fastboot3DS#50]
How can i open the menu if my home button is broken?

**Comment by profi200** [comment]
You can open "/3ds/fastbootcfg.txt" and change "BOOT_MODE = XXX" to "BOOT_MODE = Normal". This will always show the menu on boot. You can then boot normally whatever FIRM you set as autoboot by pressing A on Continue boot.

**Comment by marcotw2** [comment]
Thanks.
