### ISSUE TITLE
Enable dev mode?

### ISSUE THREAD

**Issue by Ixolaro** [derrekr/fastboot3DS#59]
Hey, i saw that some features require "dev mode" but do i need to recompile everything with a "dev flag" or smth? if so, could someone point me out every library needed to compile on a fresh Ubuntu system? (or macos or windows)

**Comment by derrekr** [comment]
To enter developer mode, navigate to the Credits section in the menu and press the Konami code button sequence.
This is currently not documented, as unexperienced users might end up bricking their system with the unlocked features.

**Comment by Anonymous941** [comment]
How do you turn it off?  I don't see anything in the config file and pressing the sequence again just turns it on again

**Comment by derrekr** [comment]
There should be a `"DEV_MODE"` key in your config file.
