### ISSUE TITLE
Godmode9 Freezes when on newest Version

### ISSUE THREAD

**Issue by Thevoododoctor** [derrekr/fastboot3DS#6]
Godemode9 freezes when launched by key combo. New 2ds XL, 11.6, USA. Boot9strap

**Comment by Cuphat** [comment]
This is a known issue, you need to use a nightly until a newer version of GM9 is released.

**Comment by profi200** [comment]
Exactly. There was some bad assumption about hardware state that broke GodMode9. It was fixed in a recent commit but there is no new release yet.
