### ISSUE TITLE
How do you enable dev mode

### ISSUE THREAD

**Issue by sandhoners123** [derrekr/fastboot3DS#7]
I want to flash something to FIRM1 but it says i need dev mode

**Comment by sandhoners123** [comment]
I got into devmode!!!!!!!

**Comment by sandhoners123** [comment]
by adding DEV_MODE = Enabled into fastbootcfg.txt

**Comment by profi200** [comment]
We don't mention how to enable it anywhere on purpose. It unlocks dangerous features we don't want noobs to mess with.

I can tell you that much:
`How to enable dev mode? *cough* K*n*m* code *cough*, entered *somewhere*.`
Quote from d0k3 on GBAtemp.

**Comment by sandhoners123** [comment]
I actually entered devmode
