### ISSUE TITLE
[Feature Request] Option to only store fastboot3DS data on NAND

### ISSUE THREAD

**Issue by Lykie** [derrekr/fastboot3DS#8]
I use multiple SD Cards and I'd like not having to set up the boot settings on first switch.

**Comment by profi200** [comment]
Although it supports configs on NAND we decided to prioritise the SD card for safety so you can override the config easily on bricks/problems.

Boot into fastboot without SD card inserted and configure it. When you insert a SD card next time the config will be copied to the SD card from NAND.

**Comment by Lykie** [comment]
Okay then. For whatever reason, the first time I inserted my other SD Card, it had me reconfigure it.

**Comment by d0k3** [comment]
You may have gotten that wrong, @Lykie. You need to fully configure fastboot 3DS without the SD card, then poweroff (or continue the boot). Only then you got the config on NAND. And this config will be copied to the SD cards you insert.

**Comment by Lykie** [comment]
I configured it without an SD Card initially. My second SD Card is just a bit touchy so it probably didn't detect it properly when I inserted it.
